version: "3"
services:
  bmsaas:
    image: alfredyang1986/bmsaas:testing
    command: --environment production --proxy http://192.168.100.174:8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "9001:4200"
    networks:
      - webnet
networks:
  webnet:
